services:
  postgres:
    image: postgres:latest
    container_name: torch_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
